### ISSUE TITLE
AlbumPoller.js / Images not grabbed by AlbumPoller

### ISSUE THREAD

**Issue by mrtimothyduong** [barrowclift/shelf#3]
Hi Marc,

I'm having issues with the AlbumArt / Data been downloaded / grabbed from iTunes to their respective folders. I've gone through the JS but there's nothing that stands out to me at the moment.

Site: https://shelf.timothyduong.me/

Technical Data:
Install Location: /home/centos/shelf
Images: /home/centos/shelf/client/images

Troubleshooting:

- No images in the "~/shelf/client/Images/record/" folder locations
- No errors in the logs (home/centos/shelf/logs/)
- Used 'sudo ./cleanLocalImageStore.sh' to no avail

Errors:
No notable errors from albumpoller.log or server.log
Eg: albumpoller: INFO - 58 records polled were already saved from a previous poll and were skipped, 0 new were found

Regards,

Timothy

**Comment by barrowclift** [comment]
Thanks so much for the information, Timothy. To clarify, are there empty folders following the format `record[0-9]+` in `~/shelf/client/Images/record/`? Or is the entire directory empty? If it's empty folders with no images, that indicates to me permissions aren't the issue, but if the entire directory's empty, permissions might be the cause.

It sounds like the logs containing the errors have been lost, unfortunately, so I'm going to ask that you kick off a resync so we can both get the logs containing the errors that (hopefully) explain why the download/save were unsuccessful. To do this:

1. Stop all shelf services with `./stop.sh`, if you haven't already
2. Execute `./clean.sh`. This will clean *everything*, including dropping the entire shelf database, so Shelf will do a full Discogs resync on next startup.
    * The script you mentioned before (`./cleanLocalImageStore.sh`) deletes the record directories and images in `/client/images/records` *but does not drop the mongo collections*, so shelf won't retry downloading record data. Effectively, it just deletes any saved album art.
3. Start all shelf services with `./start.sh` and let it run for a minute or two so it has a chance to try downloading album art for a few records.
4. Check `/logs/albumPoller.log`, you should see errors or warnings for records that failed to download or save album art for whatever reason. Please send me any relevant excerpts from that log.

**Comment by mrtimothyduong** [comment]
Hi Marc,

You're a wizard Marc!

Thanks man! That did the trick :)

Currently going through the API sync / poll now but it'll be loading soon once the rates clear up.

Site: https://shelf.timothyduong.me/

Closed and resolved :)

Regards,

Timothy

**Comment by barrowclift** [comment]
Awesome, I'm so glad to see you're now up and running, you've got a great collection! 👌🏻
